//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kort.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public int No { get; set; }
        public int ID { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<System.Guid> Personel_ID { get; set; }
        public Nullable<System.Guid> Musteri_ID { get; set; }
    
        public virtual Kort Kort { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
